assets/source/sass/layout/_header.scss
languages/simrishamn/sv_SE.po
library/Theme/GlobalNotice.php
views/partials/notice.blade.php

Add read more link

---

library/Theme/DefaultModules.php

Remove contact modules from default setting

---

assets/source/js/theme.js
assets/source/js/theme/helpers.js
library/Theme/Enqueue.php
webpack.mix.js

Include `helpers.js` in `theme.js` instead of fetching a separate asset.

Change helpers into an import

---

assets/source/sass/component/navigation/_nav.scss

Should only darken color on current node.

SIEW-223: Adjustment of side-nav coloring

---

custom-modules/NewsList/NewsList.php
library/Theme/Helper.php
library/Theme/Template.php

Automatic PSR-2 fixes via `phpcbf`.

Fix coding style for PSR-2 compliance

---

assets/source/sass/layout/_pages.scss

Serive message pages should now follow the same layout as news article pages.

SIEW-240: added basic article post styling to service message articles.

---

views/partials/footer.blade.php

Tycker detta ser vettigt ut, några invändningar? :)
Vi får väl mest testa detta under launch

added siteimprov. integration

---

webpack.mix.js

This is included in `theme.scss`, and I can't find any references to the output.

NOJIRA Remove unnecessary build of styling

---

views/partials/footer.blade.php

Hur ser detta ut? nu kallas den på samma sätt som i headern. Samtliga av parametrarna verkar ha default alternativ.

SIEW-247 Header n footer fn's are now called the same way.

---

assets/source/sass/component/news-grid/news-grid.scss

Copy pasted changes from local branch that were removed. Check padding of title and featured news excerpt. Opacity of box stripe as well.

SIEW-253 copy-pasted changes to opacity and title layout

---

assets/source/sass/layout/_main-content.scss

Minimal edit to fix responsive headline formatting.
Test by resizing browser over here: http://localhost:8000/bo-och-bygga/ or something like that.

SIEW-275 Fixed headline formatting using heigh auto

---

assets/source/sass/component/form/_input-group.scss

SIEW-276 Fixed safari mobile search formatting bug.

---

views/templates/master.blade.php

Same as #40, without changes to the link tags.

Add OpenGraph metatags to head

---

library/Theme/Customizer.php

Since we're now using our Kirki version, we should also load assets from that one.

 NOJIRA Set Kirki URL to global vendor directory 

---

library/Theme/Customizer.php

Ensures that the filters are added before they're used.

NOJIRA Add customizer filters earlier

---

library/Theme/AcfFields.php
library/Theme/AdminBar.php
library/Theme/DefaultModules.php
library/Theme/Enqueue.php
library/Theme/Language.php
library/Theme/PageHierarchy.php
library/Theme/Style.php
library/Theme/Template.php
library/Theme/TinyMCE.php

Also removes unneeded or invalid `priority` and `accepted_args` parameters.

NOJIRA Use brackets instead of array() in library

---

appveyor.yml

Version numbers are on the form `{last git tag}.{build number}`.

NOJIRA Use version numbers for all builds

---

assets/source/sass/layout/_master.scss
assets/source/sass/layout/_modules.scss

NOJIRA Styleguide breaking fixes

---

.phpcs.xml

Copied from the external project.
Really should have been here all along. :)

Add PHP Code Sniffer configuration

---

.gitignore
appveyor.yml
build.sh
package-lock.json

Prefers `npm ci`, and avoids unnecessary `npm` invocations.

NOJIRA: Improve build speed

---

package-lock.json
package.json

NOJIRA Upgrade NPM packages

---

package-lock.json
package.json

Annoying to have to customize npm run scripts every time i checkout on windows. This fixes the issue.

NOJIRA Added cross-env package

---

assets/source/sass/layout/_header.scss
assets/source/sass/subsites/naringslivsutveckling/_header.scss
assets/source/sass/subsites/simrishamnsbostader/_header.scss
assets/source/sass/subsites/visitystad/_header.scss

Was broken in https://github.com/simrishamn/simrishamn-child/pull/96 due to changed class names

SIEW-347 Fixed subsites css

---

.eslintrc.yml
assets/source/js/theme.js
assets/source/js/theme/translate.js
assets/source/sass/layout/_translate.scss
assets/source/sass/subsites/visitystad/_header.scss
assets/source/sass/theme.scss
bem-views/partials/translate-modal.blade.php
bem-views/templates/master.blade.php
bem-views/widget/translate-button.blade.php
library/Theme/Application.php
library/Theme/Widget.php
library/Widget/TranslateButton.php

Fixes the modal not showing in mobile view.
In essence the same as #106, but reorganized.

SIEW-364: Redo translation modal

---

bem-views/archive.blade.php
bem-views/front-page.blade.php
bem-views/partials/article.blade.php
bem-views/partials/blog/type/post-single.blade.php
bem-views/templates/master.blade.php

Fixed problem regarding missing link destination of main-content.

WCAG Fixed problem regarding missing link destination. 

---

assets/source/sass/layout/_master.scss

WCAG more fixes. Changed colors to achive correct contrast ratio.

SIEW-392 WCAG changed colors on linkbox modules text.

---

bem-views/full-width.blade.php

Trying again since the last PR didn't work in AppVeyor.

SIEW-373 WCAG Fixed problem with duplicated IDs.

---

bem-views/page.blade.php

Commit to test AppVeyor.
